spring:
  application:
    name: workload-identity
  cloud:
    azure:
      profile:
        tenant-id: 46d94fba-20cf-4c54-bc37-19ad68bb0dd5
      credential:
        managed-identity-enabled: true
        client-id: c8c406a9-bfdd-45d9-84af-df9dc55be555
      servicebus:
        namespace: m01servicebus
        resource:
          resource-group: matt_learn
    function:
      definition: consume;supply;
    stream:
      bindings:
        consume-in-0:
          destination: queue1
        supply-out-0:
          destination: queue1
      poller:
        fixed-delay: 60000
        initial-delay: 0
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
              entity-type: queue
          supply-out-0:
            producer:
              entity-type: queue
  
  datasource:
    url: jdbc:sqlserver://m01azuresqlserver.database.windows.net:1433;database=m01database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;Authentication=ActiveDirectoryDefault;user=c8c406a9-bfdd-45d9-84af-df9dc55be555
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
asb:
  entity:
    name: "queue1"
server:
  port: 8080

logging:
  level:
    root: info
    com.azure.core: error
