spring:
  application:
    name: workload-identity
  data:
    redis:
      host: m01.redis.cache.windows.net
      port: 6380
      username: 3ee2508b-b06f-4e6a-8fba-4e246b147357
      azure:
        passwordless-enabled: true
      ssl:
        enabled: true