spring:
  application:
    name: workload-identity
  data:
    redis:
      host: m01redis.redis.cache.windows.net
      port: 6380
      azure:
        passwordless-enabled: true
      ssl:
        enabled: true
  cloud:
    azure:
      credential:
        client-id: a61679a0-523b-407c-ab40-fc98c6664ba3

logging:
  level:
    com:
      microsoft: debug
      azure: debug
    root: info

server:
  port: 8080