spring:
  application:
    name: workload-identity
  data:
    redis:
      host: m01.redis.cache.windows.net
      port: 6380
      azure:
        passwordless-enabled: true
      ssl:
        enabled: true

debug: true

logging:
  level:
    com:
      microsoft: debug
      azure: debug