spring:
  application:
    name: workload-identity
  cloud:
    azure:
      profile:
        subscription-id: f7d9ba33-70f6-4106-bfc9-9db2c87691a0
        tenant-id: 3b3079ee-db4e-4a06-8af0-a71bc0abb502
      credential:
#        managed-identity-enabled: true #when start on local, need to omit this setting
        client-id: a61679a0-523b-407c-ab40-fc98c6664ba3
      servicebus:
        namespace: m01servicebus
        resource:
          resource-group: matt_learn
    function:
      definition: consume;supply;
    stream:
      bindings:
        consume-in-0:
          destination: queue1
        supply-out-0:
          destination: queue1
      poller:
        fixed-delay: 60000
        initial-delay: 0
      servicebus:
        bindings:
          consume-in-0:
            consumer:
              auto-complete: false
              entity-type: queue
          supply-out-0:
            producer:
              entity-type: queue
  
  datasource:
    url: jdbc:sqlserver://m01azuresqlserver.database.windows.net:1433;database=m01database;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;Authentication=ActiveDirectoryDefault;user=a61679a0-523b-407c-ab40-fc98c6664ba3
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    database-platform: org.hibernate.dialect.SQLServerDialect
    hibernate:
      ddl-auto: update
asb:
  entity:
    name: "queue1"
server:
  port: 8080

logging:
  level:
    root: info
    com.azure.core: error
